version: "3.8"
services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local
